import { useMemo, useState } from 'react';
import { useStore } from '../../context/useStore';
import ProductCard from './ProductCard';

export function CustomerSidebar({ view, navigate, count, orderCount, returnCount, ticketCount, compareCount = 0 }) {
  const groups = [
    ['SHOP', [['Shop','⌂'],['Deals','％'],['Buy Again','↻'],['Wishlist','♡']]],
    ['COMPARE', [['Compare','⇄']]],
    ['YOUR ACCOUNT', [['Orders','▤'],['Returns','↩'],['Addresses','⌖'],['Support','?'],['Profile','◉']]],
    ['PURCHASE', [['Cart','▣']]],
  ];
  const badge = { Cart: count, Orders: orderCount, Returns: returnCount, Support: ticketCount, Compare: compareCount };
  return <aside className="market-sidebar" aria-label="Customer navigation">{groups.map(([title,items])=><div className="market-sidebar__group" key={title}><h2>{title}</h2>{items.map(([name,icon])=><button type="button" key={name} className={view===name?'is-active':''} onClick={()=>navigate(name)} aria-current={view===name?'page':undefined}><span>{icon}</span>{name}{badge[name]>0&&<b>{badge[name]}</b>}</button>)}</div>)}<div className="market-sidebar__help"><strong>Need a hand?</strong><p>Our store team can help with orders, returns, and product questions.</p><button type="button" onClick={()=>navigate('Support')}>Contact support</button></div></aside>;
}

export default function CustomerHub({ view, orders, user, addresses, setAddresses, openProduct, addToCart, toggleWishlist, wishlist, setCouponCode, navigate }) {
  const { products, promotions, returnRequests, supportTickets, createReturnRequest, createSupportTicket, replyToSupportTicket } = useStore();
  const [form, setForm] = useState({});
  const [message, setMessage] = useState('');
  const [selectedOrder, setSelectedOrder] = useState('');
  const [selectedItem, setSelectedItem] = useState('');
  const myReturns=returnRequests.filter(item=>item.customerEmail===user.email);
  const myTickets=supportTickets.filter(item=>item.customerEmail===user.email);
  const activeDeals=promotions.filter(p=>p.active&&(!p.expiresAt||new Date(`${p.expiresAt}T23:59:59`)>new Date())&&(!p.usageLimit||p.usedCount<p.usageLimit));
  const purchased=useMemo(()=>{const ids=new Set(orders.flatMap(order=>order.items?.map(item=>item.productId)||[]));return products.filter(product=>ids.has(product.id)&&!product.isArchived);},[orders,products]);
  const saveAddress=(event)=>{event.preventDefault();const next={...form,id:form.id||`ADDR-${Date.now()}`,isDefault:addresses.length===0||form.isDefault};setAddresses(previous=>previous.some(item=>item.id===next.id)?previous.map(item=>item.id===next.id?next:{...item,isDefault:next.isDefault?false:item.isDefault}):[...previous.map(item=>({...item,isDefault:next.isDefault?false:item.isDefault})),next]);setForm({});setMessage('Address saved.');};
  const submitReturn=(event)=>{event.preventDefault();const [orderId,productId]=selectedItem.split('|');const result=createReturnRequest({orderId,productId,quantity:form.quantity||1,reason:form.reason||'Changed my mind',details:form.details||''});setMessage(result.success?'Return request submitted.':result.error);};
  const submitTicket=(event)=>{event.preventDefault();const result=createSupportTicket({subject:form.subject||'',message:form.message||'',orderId:form.orderId||''});setMessage(result.success?'Your message was sent.':result.error);if(result.success)setForm({});};
  if(view==='Deals')return <section className="hub-page"><div className="page-heading"><div><p className="eyebrow">LIMITED-TIME SAVINGS</p><h1>Deals & coupons</h1><p>Use a store coupon at checkout. Current promotions come directly from the merchant.</p></div></div>{activeDeals.length?<div className="customer-deal-grid">{activeDeals.map(p=><article className="customer-deal" key={p.id}><span>SHOPMETRICS OFFER</span><strong>{p.discountType==='percent'?`${p.discountValue}% off`:`$${Number(p.discountValue).toFixed(2)} off`}</strong><code>{p.code}</code><p>{Number(p.minimumOrder)>0?`On orders over $${Number(p.minimumOrder).toFixed(2)}`:'No minimum purchase'}{p.expiresAt?` · Expires ${p.expiresAt}`:''}</p><button type="button" className="primary-action" onClick={()=>{setCouponCode(p.code);navigate('Cart');}}>Apply at checkout</button></article>)}</div>:<div className="hub-empty"><h2>No active offers right now</h2><p>Check back later for store promotions.</p></div>}<h2 className="hub-section-title">Popular picks</h2><div className="product-grid">{products.filter(p=>!p.isArchived).slice(0,4).map(product=><ProductCard key={product.id} product={product} onOpen={openProduct} onAddToCart={addToCart} isSaved={wishlist.includes(product.id)} onToggleSaved={toggleWishlist}/>)}</div></section>;
  if(view==='Buy Again')return <section className="hub-page"><div className="page-heading"><div><p className="eyebrow">YOUR SHOPPING HISTORY</p><h1>Buy again</h1><p>Quickly find products from your previous orders.</p></div></div>{purchased.length?<div className="product-grid">{purchased.map(product=><ProductCard key={product.id} product={product} onOpen={openProduct} onAddToCart={addToCart} isSaved={wishlist.includes(product.id)} onToggleSaved={toggleWishlist}/>)}</div>:<div className="hub-empty"><h2>Your purchase list is empty</h2><button className="primary-action" onClick={()=>navigate('Shop')}>Explore the shop</button></div>}</section>;
  if(view==='Addresses')return <section className="hub-page"><div className="page-heading"><div><p className="eyebrow">DELIVERY PREFERENCES</p><h1>Your addresses</h1><p>Save delivery locations and choose one at checkout.</p></div></div><form className="hub-form" onSubmit={saveAddress}><h2>{form.id?'Edit address':'Add a delivery address'}</h2><div className="hub-form-grid">{[['recipientName','Full name'],['phone','Phone'],['streetAddress','Street address'],['city','City'],['region','State / province'],['postalCode','Postal code']].map(([key,label])=><label key={key}>{label}<input required value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label className="hub-check"><input type="checkbox" checked={!!form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Set as default</label><button className="primary-action">Save address</button>{message&&<p role="status">{message}</p>}</form><div className="address-list">{addresses.map(address=><article key={address.id}><div><strong>{address.recipientName}</strong>{address.isDefault&&<span className="address-default">DEFAULT</span>}<p>{address.streetAddress}<br/>{address.city}, {address.region} {address.postalCode}<br/>{address.phone}</p></div><div><button type="button" onClick={()=>setForm(address)}>Edit</button><button type="button" onClick={()=>setAddresses(items=>items.filter(item=>item.id!==address.id).map((item,index)=>({...item,isDefault:index===0?true:item.isDefault})))}>Remove</button></div></article>)}</div></section>;
  if(view==='Returns')return <section className="hub-page"><div className="page-heading"><div><p className="eyebrow">ORDER SUPPORT</p><h1>Returns & refunds</h1><p>Request a return for an eligible delivered order and follow progress here.</p></div></div><form className="hub-form" onSubmit={submitReturn}><h2>Start a return</h2><label>Delivered order<select required value={selectedOrder} onChange={e=>{setSelectedOrder(e.target.value);setSelectedItem('');}}><option value="">Choose an order</option>{orders.filter(o=>o.status==='Delivered').map(order=><option key={order.id} value={order.id}>{order.id} · {new Date(order.date).toLocaleDateString()}</option>)}</select></label><label>Item to return<select required value={selectedItem} onChange={e=>setSelectedItem(e.target.value)}><option value="">Choose an item</option>{orders.find(o=>o.id===selectedOrder)?.items?.map(item=><option key={item.productId} value={`${selectedOrder}|${item.productId}`}>{item.name} · Qty {item.quantity}</option>)}</select></label><div className="hub-form-grid"><label>Quantity<input type="number" min="1" value={form.quantity||1} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Reason<select value={form.reason||'Changed my mind'} onChange={e=>setForm({...form,reason:e.target.value})}>{['Changed my mind','Damaged or defective','Wrong item','Not as described','Arrived late','Other'].map(reason=><option key={reason}>{reason}</option>)}</select></label></div><label>Details<textarea rows="3" value={form.details||''} onChange={e=>setForm({...form,details:e.target.value})}/></label><button className="primary-action">Request return</button>{message&&<p role="status">{message}</p>}</form><div className="hub-record-list">{myReturns.map(item=><article key={item.id}><div><strong>{item.productName}</strong><p>{item.id} · {item.orderId} · Qty {item.quantity}</p></div><span className={`return-state return-state--${item.status.toLowerCase()}`}>{item.status}</span></article>)}</div></section>;
  if(view==='Support')return <section className="hub-page"><div className="page-heading"><div><p className="eyebrow">WE’RE HERE TO HELP</p><h1>Customer support</h1><p>Send a question to the merchant and continue the conversation here.</p></div></div><form className="hub-form" onSubmit={submitTicket}><h2>Contact the store</h2><label>Subject<input required value={form.subject||''} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Related order (optional)<select value={form.orderId||''} onChange={e=>setForm({...form,orderId:e.target.value})}><option value="">General question</option>{orders.map(order=><option key={order.id}>{order.id}</option>)}</select></label><label>Message<textarea required rows="4" value={form.message||''} onChange={e=>setForm({...form,message:e.target.value})}/></label><button className="primary-action">Send message</button>{message&&<p role="status">{message}</p>}</form><div className="hub-record-list">{myTickets.map(ticket=><article key={ticket.id} className="customer-ticket"><div><strong>{ticket.subject}</strong><p>{ticket.id} · {ticket.status}{ticket.orderId?` · ${ticket.orderId}`:''}</p>{ticket.messages.map((item,index)=><p className="ticket-message" key={index}><b>{item.author}:</b> {item.message}</p>)}</div><form onSubmit={event=>{event.preventDefault();replyToSupportTicket(ticket.id,form[`reply-${ticket.id}`]);setForm({...form,[`reply-${ticket.id}`]:''});}}><input aria-label="Reply" placeholder="Write a reply" value={form[`reply-${ticket.id}`]||''} onChange={e=>setForm({...form,[`reply-${ticket.id}`]:e.target.value})}/><button>Reply</button></form></article>)}</div></section>;
  return null;
}
